import Head from "next/head";
import { Flex } from "@chakra-ui/react";
import Container from "../components/Container";
import { Hero, SubHero } from "../components/Hero";
import Example from "../components/Example";

export default function Home() {
	return (
		<Flex flexDir="column">
			<Head>
				<title>UT</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<Container>
				<Hero />
				<SubHero title="VINCULACIÓN" src="/images/subHero1.jpeg" />
			</Container>
		</Flex>
	);
}
